package Vistas;

import Datos.AlojamientoDatos;
import Datos.CiudadDatos;
import Entidades.Alojamiento;
import Entidades.Ciudad;
import Entidades.Servicio;
import Entidades.TipoAlojamiento;
import com.toedter.calendar.JDateChooser;
import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Image;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.sql.Date;
import java.text.SimpleDateFormat;
import javax.swing.AbstractCellEditor;
import javax.swing.DefaultCellEditor;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableColumn;

public class GestionAlojamiento extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo = new DefaultTableModel() {
        public boolean isCellEditable(int fila, int columna) {
            if (columna != 0 && columna!=1 && columna != 7) {
                return true;
            } else {
                return false;
            }
        }
    };

    private class JDateChooserCellEditor extends AbstractCellEditor implements TableCellEditor {

        private JDateChooser dateChooser;
        private java.util.Date selectedDate;

        public JDateChooserCellEditor() {
            dateChooser = new JDateChooser();
            dateChooser.setDateFormatString("yyyy-MM-dd"); // Establece el formato de fecha según tus necesidades
            // Agregar un PropertyChangeListener para capturar la fecha seleccionada
            dateChooser.addPropertyChangeListener("date", new PropertyChangeListener() {
                @Override
                public void propertyChange(PropertyChangeEvent evt) {
                    if (evt.getPropertyName().equals("date")) {
                        selectedDate = (java.util.Date) evt.getNewValue();
                        stopCellEditing();
                    }
                }
            });
        }

        @Override
        public Object getCellEditorValue() {
            return selectedDate;
        }

        @Override
        public Component getTableCellEditorComponent(JTable table, Object value, boolean isSelected, int row, int column) {
            if (value instanceof java.util.Date) {
                selectedDate = (java.util.Date) value;
                dateChooser.setDate(selectedDate);
            }
            return dateChooser;
        }
    }

    private class DateRenderer extends DefaultTableCellRenderer {

        private SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");

        @Override
        protected void setValue(Object value) {
            if (value instanceof java.util.Date) {
                setText(dateFormat.format((java.util.Date) value));
            } else {
                super.setValue(value);
            }
        }
    }

    /**
     * Creates new form GestionAlojamiento
     */
    public GestionAlojamiento() {
        initComponents();
        textMod(false);
        cargarComboxAlo();
        cagarComboxSer();
        cagarComboxCiu();
        armarCabezera();
        modelo.setRowCount(0);
        cargarTabla();
        jTable1.setSelectionBackground(Color.green);
        agregarcomboBox(5, this.jTable1);
        agregarcomboalo(4, this.jTable1);
        elejirColumanasFechas(2, 3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/Imagenes/fondo_alojamiento2.jpg"));
        Image image = icon.getImage();
        jPanel1 = new javax.swing.JPanel(){
            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jbAgregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jbModificar = new javax.swing.JButton();
        jbEliminar = new javax.swing.JButton();
        jcCiuDestino = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jcServicio = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jtImporteDiario = new javax.swing.JTextField();
        jbNuevo = new javax.swing.JButton();
        jcCiuBuscar = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jdateFechaIngre = new com.toedter.calendar.JDateChooser();
        jdateFechaSalida = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jcAlo = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Gestion de Alojamiento");

        jPanel1.setBackground(new java.awt.Color(153, 0, 51));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Gestion De Alojamiento");
        jLabel1.setOpaque(true);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Ciudad Destino:");
        jLabel2.setOpaque(true);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Fecha de ingreso:");
        jLabel3.setOpaque(true);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Servicio:");
        jLabel5.setOpaque(true);

        jbAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/add.png"))); // NOI18N
        jbAgregar.setText("Agregar");
        jbAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel7.setText("Buscar Alojamiento por Ciudad:");
        jLabel7.setOpaque(true);

        jbModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/update_file.png"))); // NOI18N
        jbModificar.setText("Actualizar");
        jbModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarActionPerformed(evt);
            }
        });

        jbEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/delete2.png"))); // NOI18N
        jbEliminar.setText("Eliminar");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Fecha de Salida:");
        jLabel6.setOpaque(true);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Importe Diario:");
        jLabel8.setOpaque(true);

        jbNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/new-page.png"))); // NOI18N
        jbNuevo.setText("Nuevo");
        jbNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoActionPerformed(evt);
            }
        });

        jcCiuBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcCiuBuscarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("$");
        jLabel4.setOpaque(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/exit.png"))); // NOI18N
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("Alojamiento:");
        jLabel9.setOpaque(true);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel10.setText("Crear Alojamiento");
        jLabel10.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jcCiuDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(67, 67, 67)
                                        .addComponent(jcServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jcAlo, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtImporteDiario, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(7, 7, 7)
                                        .addComponent(jdateFechaIngre, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(jdateFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(26, 26, 26))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbEliminar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jcCiuBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jbNuevo)
                                        .addGap(18, 18, 18)
                                        .addComponent(jbAgregar)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbModificar, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 837, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(315, 315, 315)
                .addComponent(jLabel1)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jcCiuBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbEliminar)
                            .addComponent(jbModificar))
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addGap(30, 30, 30)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jdateFechaIngre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jcCiuDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jcAlo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addComponent(jdateFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jcServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel4)
                    .addComponent(jtImporteDiario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbNuevo)
                            .addComponent(jbAgregar))
                        .addGap(25, 25, 25))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoActionPerformed
        // Nuevo
        textMod(true);
    }//GEN-LAST:event_jbNuevoActionPerformed

    private void jbAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarActionPerformed
        // Agregar
        try {
            if (this.jtImporteDiario.getText().isEmpty() || this.jdateFechaIngre.getDate() == null || this.jdateFechaSalida.getDate() == null) {
                JOptionPane.showMessageDialog(null, "No deben quedar campos vacíos", "Loco Fíjate", JOptionPane.ERROR_MESSAGE);
                return;
            }
            Ciudad ciu = (Ciudad) this.jcCiuDestino.getSelectedItem();
            java.util.Date fIng = this.jdateFechaIngre.getDate(); // Obtener la fecha de ingreso como java.util.Date
            java.util.Date fSal = this.jdateFechaSalida.getDate(); // Obtener la fecha de salida como java.util.Date
            if (fIng.after(fSal)) {
                JOptionPane.showMessageDialog(null, "La fecha de ingreso tiene que ser antes de la fecha de salida", "Loco Fíjate", JOptionPane.ERROR_MESSAGE);
                limpiar();
                return;
            }
            TipoAlojamiento alo = (TipoAlojamiento) this.jcAlo.getSelectedItem();
            Servicio ser = (Servicio) this.jcServicio.getSelectedItem();
            double imp = Double.parseDouble(this.jtImporteDiario.getText());
            if(imp<0){
                JOptionPane.showMessageDialog(null, "Para el importe debe agregar números positivos");
                limpiar();
            }else{
                
            
            boolean est = true;
            // Convertir java.util.Date a java.sql.Date
            java.sql.Date sqlDateIng = new java.sql.Date(fIng.getTime());
            java.sql.Date sqlDateSal = new java.sql.Date(fSal.getTime());
            // Crear un objeto Alojamiento usando las fechas convertidas a java.sql.Date
            Alojamiento alojamiento = new Alojamiento(ciu, sqlDateIng.toLocalDate(), sqlDateSal.toLocalDate(), alo, ser, imp, est);
            AlojamientoDatos.alojamientoGuardar(alojamiento);
            limpiar();
            modelo.setRowCount(0);
            cargarTabla();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Solo números positivos" + e.getMessage(), "Date cuenta capo solo NUMEROS", JOptionPane.ERROR_MESSAGE);
            limpiar();
        }
        textMod(false);
    }//GEN-LAST:event_jbAgregarActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        // Eliminar
        int filaSelecionada = this.jTable1.getSelectedRow();
        if (filaSelecionada != -1) { // Verifica si se ha seleccionado una fila válida
            int idAlo = Integer.parseInt(modelo.getValueAt(filaSelecionada, 0).toString());
            AlojamientoDatos.eliminarAlojamiento(idAlo);
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione una fila antes de Eliminar Ciudad", "Error", JOptionPane.ERROR_MESSAGE);
        }
        modelo.setRowCount(0);
        cargarTabla();
    }//GEN-LAST:event_jbEliminarActionPerformed

    private void jbModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarActionPerformed
        // Modificar
        int filaSelecionada = this.jTable1.getSelectedRow();
        if (filaSelecionada != -1) { // Verifica si se ha seleccionado una fila válida
            int idAlo = Integer.parseInt(modelo.getValueAt(filaSelecionada, 0).toString());
            String ciu = modelo.getValueAt(filaSelecionada, 1).toString();

            // Obtén la fecha como un objeto java.util.Date
            java.util.Date utilDateInicio = (java.util.Date) modelo.getValueAt(filaSelecionada, 2);
            java.util.Date utilDateSalida = (java.util.Date) modelo.getValueAt(filaSelecionada, 3);
            
            if (utilDateInicio.after(utilDateSalida)) {
                JOptionPane.showMessageDialog(null, "La fecha de ingreso tiene que ser antes de la fecha de salida", "Loco Fíjate", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Convierte las fechas de java.util.Date a java.sql.Date
            java.sql.Date sqlDateInicio = new java.sql.Date(utilDateInicio.getTime());
            java.sql.Date sqlDateSalida = new java.sql.Date(utilDateSalida.getTime());

            TipoAlojamiento alo = (TipoAlojamiento) modelo.getValueAt(filaSelecionada, 4);
            Servicio ser = (Servicio) modelo.getValueAt(filaSelecionada, 5);
            double imp = Double.parseDouble(modelo.getValueAt(filaSelecionada, 6).toString());
            String est = modelo.getValueAt(filaSelecionada, 7).toString();

            AlojamientoDatos.modificarAlojamiento(new Alojamiento(idAlo, CiudadDatos.buscarCiudad(ciu), sqlDateInicio.toLocalDate(), sqlDateSalida.toLocalDate(), alo, ser, imp, activo1(est)));
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione una fila antes de intentar actualizar.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        modelo.fireTableDataChanged();

    }//GEN-LAST:event_jbModificarActionPerformed

    private void jcCiuBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcCiuBuscarActionPerformed
        // BuscarCombox
        modelo.setRowCount(0);
        Ciudad ciuSelecionada = (Ciudad) this.jcCiuBuscar.getSelectedItem();
        for (Alojamiento alo : AlojamientoDatos.listaAlojamientosxCiudadActiva()) {
            if (alo.getCiuDestino().getNombre().equalsIgnoreCase(ciuSelecionada.getNombre())) {
                modelo.addRow(new Object[]{alo.getIdAlojamiento(), alo.getCiuDestino().getNombre(), alo.getFechaIngreso(), alo.getFechaSalida(), alo.getAlojamiento(), alo.getServicio(), alo.getImporteDiario(), activo(alo.isEstado())});

            }
        }
    }//GEN-LAST:event_jcCiuBuscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbAgregar;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbModificar;
    private javax.swing.JButton jbNuevo;
    private javax.swing.JComboBox<TipoAlojamiento> jcAlo;
    private javax.swing.JComboBox<Ciudad> jcCiuBuscar;
    private javax.swing.JComboBox<Ciudad> jcCiuDestino;
    private javax.swing.JComboBox<Servicio> jcServicio;
    private com.toedter.calendar.JDateChooser jdateFechaIngre;
    private com.toedter.calendar.JDateChooser jdateFechaSalida;
    private javax.swing.JTextField jtImporteDiario;
    // End of variables declaration//GEN-END:variables

    private void textMod(boolean ok) {
        this.jtImporteDiario.setEditable(ok);
        this.jcCiuDestino.setEnabled(ok);
        this.jcAlo.setEnabled(ok);
        this.jcServicio.setEnabled(ok);
        this.jdateFechaIngre.setEnabled(ok);
        this.jdateFechaSalida.setEnabled(ok);

    }

    private void armarCabezera() {
        modelo.addColumn("IdAlojamiento");
        modelo.addColumn("Destino");
        modelo.addColumn("Ingreso");
        modelo.addColumn("Salida");
        modelo.addColumn("Alojamiento");
        modelo.addColumn("Servicio");
        modelo.addColumn("Importe Diario");
        modelo.addColumn("Activo");
        this.jTable1.setModel(modelo);
    }

    private void limpiar() {
        this.jtImporteDiario.setText("");
        this.jdateFechaIngre.setDate(null);  // Establece la fecha de ingreso como null
        this.jdateFechaSalida.setDate(null);  // Establece la fecha de salida como null
    }

    private String activo(boolean ok) {
        if (ok) {
            return "Si";
        }
        return "No";
    }

    private boolean activo1(String ok) {
        if (ok.equalsIgnoreCase("true")) {
            return true;
        }
        return false;
    }

    private void cargarTabla() {
        for (Alojamiento alo : AlojamientoDatos.listaAlojamientosxCiudadActiva()) {

            int id = alo.getIdAlojamiento();
            String ciu = alo.getCiuDestino().getNombre();
            Date fIng = Date.valueOf(alo.getFechaIngreso().toString());
            Date fSal = Date.valueOf(alo.getFechaSalida().toString());
            TipoAlojamiento aloj = alo.getAlojamiento();
            Servicio ser = alo.getServicio();
            double imp = alo.getImporteDiario();
            boolean est = alo.isEstado();
            modelo.addRow(new Object[]{id, ciu, fIng, fSal, aloj, ser, imp, activo(est)});

        }
    }

    private void cagarComboxSer() {
        this.jcServicio.addItem(Servicio.BASICO);
        this.jcServicio.addItem(Servicio.COMPLETO);
        this.jcServicio.addItem(Servicio.TODO_INCLUIDO);
    }

    private void cagarComboxCiu() {
        for (Ciudad ciu : CiudadDatos.listarCiu()) {
            if (ciu.isEstado() == true) {
                this.jcCiuDestino.addItem(ciu);
                this.jcCiuBuscar.addItem(ciu);
            }
        }
    }

    private void agregarcomboBox(int columna, JTable tabla) {
        TableColumn tc = tabla.getColumnModel().getColumn(columna);
        JComboBox comboBox = new JComboBox();
        comboBox.addItem(Servicio.BASICO);
        comboBox.addItem(Servicio.COMPLETO);
        comboBox.addItem(Servicio.TODO_INCLUIDO);
        tc.setCellEditor(new DefaultCellEditor(comboBox));
    }

    private void cargarComboxAlo() {
        this.jcAlo.addItem(TipoAlojamiento.HOTEL);
        this.jcAlo.addItem(TipoAlojamiento.DEPARTAMENTO);
        this.jcAlo.addItem(TipoAlojamiento.CABAÑA);

    }

    private void agregarcomboalo(int columna, JTable tabla) {
        TableColumn tc = tabla.getColumnModel().getColumn(columna);
        JComboBox comboBox = new JComboBox();
        comboBox.addItem(TipoAlojamiento.HOTEL);
        comboBox.addItem(TipoAlojamiento.DEPARTAMENTO);
        comboBox.addItem(TipoAlojamiento.CABAÑA);
        tc.setCellEditor(new DefaultCellEditor(comboBox));
    }

    private void elejirColumanasFechas(int colum1, int colum2) {
        GestionAlojamiento.JDateChooserCellEditor fechaIngreso = new GestionAlojamiento.JDateChooserCellEditor();
        GestionAlojamiento.JDateChooserCellEditor FechaSalida = new GestionAlojamiento.JDateChooserCellEditor();
        this.jTable1.getColumnModel().getColumn(colum1).setCellEditor(fechaIngreso);
        this.jTable1.getColumnModel().getColumn(colum2).setCellEditor(FechaSalida);
        // Configura el renderizador para mostrar las fechas en el formato deseado en la tabla
        this.jTable1.getColumnModel().getColumn(colum1).setCellRenderer(new GestionAlojamiento.DateRenderer());
        this.jTable1.getColumnModel().getColumn(colum2).setCellRenderer(new GestionAlojamiento.DateRenderer());
    }

//    private void borrarFila(Alojamiento alo) {
//        int f = this.jTable1.getRowCount() - 1;
//        for (; f >= 0; f--) {
//            if (alo.getCiuDestino() == null) {
//                modelo.removeRow(f);
//            }
//        }
//    }
}//Fin class
